version: '3'
services:
    web:
        image: nginx:alpine
        ports:
            - 8081:80
        volumes:
            - ./public_html:/public_html
            - ./projects:/projects
            - ./conf.d:/etc/nginx/conf.d
        networks:
            - nginxphp
    php:
        image: php:7.2-fpm-alpine
        volumes:
            - ./public_html:/public_html
            - ./projects:/projects
        expose:
            - 9000
        networks:
            - nginxphp
    composer:
        image: composer:latest
        volumes: 
            - ./public_html:/public_html
            - ./projects:/projects
        working_dir: /projects
        command: ping localhost
        tty: true
        stdin_open: true
        networks: 
            - nginxphp
networks:
    nginxphp:
