version: '3'
services:
    web:
        image: nginx:alpine
        depends_on:
            - php
        ports:
            - 8081:80
        volumes:
            - ./public_html:/public_html
            - ./projects:/projects
            - ./conf.d:/etc/nginx/conf.d
        networks:
            - nginxphp
    php:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./public_html:/public_html
            - ./projects:/projects
        working_dir: /projects
        tty: true
        expose:
            - 9000
        networks:
            - nginxphp
networks:
    nginxphp:
